Updating Shifts API Docs
bullhorn/rest-api-docs pull request #121
Opened 2022-03-08 20:50 UTC by worycatts

Closes out [BH-74372](https://jira.bullhorn.com/browse/BH-74372)

Added API docs for shifts related entities and updated the Notes entity with new fields

Shift (shift definition)
ShiftPosition
JobShift
CandidateAvailability
CandidatePreferences
ShiftType
JobShiftSubmission
JobShiftAssignment
Note (add JobShifts as an entity reference)

2022-03-10 21:19 UTC, Allblues requested changes

2022-03-10 21:19 UTC, Allblues commented on source/includes/entityref/_candidateshiftpreference.md
> +CandidatePreferences is used for storing a candidate's preferences for times and days when they want to work in association with the shiftTypes that are configured.
Change to something like:
Stores a candidate's preferences for times and days to work in association with the shiftTypes that are configured.

If ShiftType is an entity, use a capital S on it.

2022-03-10 21:19 UTC, Allblues commented on source/includes/entityref/_candidateshiftpreference.md
> +            <td>Candidate associated to Shift Preferences.</td>
Here and elsewhere use the camelcased real entity name.

2022-03-10 21:19 UTC, Allblues commented on source/includes/entityref/_jobshift.md
> +JobShift is the main entity for shift scheduling and is used for storing start & end times, references to the clientCorporation, job, and other details for the shift (such as location, name, etc).
Change to something like:
The main entity for shift scheduling. Used for storing start and end times, references to the ClientCorporation, JobOrder, and other details for the shift such as location, name, and so forth.

Throughout the doc, use the real camelcased entity name where appropriate.

2022-03-10 21:19 UTC, Allblues commented on source/includes/entityref/_jobshift.md
> +            <td>Ratio of Assigned Candidates to Openings on the Job Shift.</td>
Change to:
Ratio of assigned Candidates to Openings on the JobShift.

What is Openings? Is it an actual entity or just a general thing? If general, use lowercase on it.

2022-03-10 21:19 UTC, Allblues commented on source/includes/entityref/_jobshift.md
> +            <td>Job Shift Submission associated to a shift. Job Shift Submission is created when Offering a Candidate a Shift, before the Shift Submission is promoted to a Shift Assignment.</td>
Same comment about entity names as elsewhere. Seems "Offering" should be lowercase.

2022-03-10 21:19 UTC, Allblues commented on source/includes/entityref/_jobshift.md
> +            <td>The shift types the associated Job Shift spans over. Shift Types are designated in Shift Admin.</td>
Maybe try:
The ShiftTypes over which the associated JobShift spans.

Is Shift Admin an real application name?

2022-03-10 21:19 UTC, Allblues commented on source/includes/entityref/_jobshiftassignment.md
> +JobShiftAssignment ties the candidate to a JobShift and also allows for storing time capture details (such as actualStartTime and actualEndTime).
Change to:
Ties the Candidate to a JobShift and also allows for storing time capture details such as actualStartTime and actualEndTime.

2022-03-10 21:19 UTC, Allblues commented on source/includes/entityref/_shift.md
> +            <td>Client Corporation associated to the Shift Defintion.</td>
Fix typo  - Defintion should be Definition

2022-03-10 21:19 UTC, Allblues commented on source/includes/entityref/_shiftposition.md
> +ShiftPosition is used to create more specific shifts tied to a single job. Also can be used for storing rate information that is tied to the jobShift.
Change to:
Used to create more specific Shifts tied to a single JobOrder. Also can be used for storing rate information that is tied to the JobShift.

I'm not sure if you want real entity names like used above.

2022-03-10 21:19 UTC, Allblues commented on source/includes/entityref/_shifttype.md
> +ShiftType is an entity set at the corporation level to define various shift time intervals (Morning, Afternoon, Evening, Overnight, etc.) - used for setting candidatePreferences.
Try to avoid "etc" and instead use "and so forth".

2022-03-11 21:20 UTC, worycatts commented on source/includes/entityref/_candidateavailability.md
> +            <td>Candidate associated to this availability.</td>
fixed.

2022-03-14 14:00 UTC, merged