Add new BTE fields to placement entity reference
bullhorn/rest-api-docs pull request #135
Opened 2022-06-27 20:19 UTC by tiffanineyland

Adding BTE Sync Status and BTE Last Sync Date fields to Placement entity documentation per [BH-76522](https://jira.bullhorn.com/browse/BH-76522)

2022-06-28 18:36 UTC, tiffanineyland commented on source/includes/entityref/_placement.md
> +| bteSyncStatus | String (100) | BTE Sync Status allows for viewing whether a Bullhorn placement was synced to BTE successfully, pending, or if there was an issue. | X | X |
Thanks for your feedback! Just committed some updates based on your comments.

2022-06-29 13:09 UTC, Allblues commented on source/includes/entityref/_placement.md
> +| bteSyncStatus | String | Allows for viewing whether a Bullhorn placement was synced to BTE successfully, pending, or if there was an issue. This field should only appear if a corporation is WFR ena
Can you get the real String length from a rest meta call and include it?

2022-06-30 17:50 UTC, Allblues requested changes

2022-06-30 19:04 UTC, Allblues approved these changes

2022-07-01 16:47 UTC, merged